dependencies:
  - name: elasticsearch
    version: ^19.10.3
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
  - name: mongodb
    version: ^13.15.4
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
